# Generated by Django 6.0.4 on 2026-05-03 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loggarden', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='logentry',
            name='logentry_extra_gin_idx',
        ),
    ]
