# Generated by Django 6.0.4 on 2026-05-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loggarden', '0002_remove_logentry_logentry_extra_gin_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='method',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
