# Generated by Django 6.0.4 on 2026-05-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loggarden', '0003_alter_logentry_method_alter_logentry_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='exception_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='exception_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='extra',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='traceback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
